// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZs_IgnqW9ReEYprmZLYHH5MLRVJdXMFA',
    appId: '1:887752712451:web:0889f60108657201ff8936',
    messagingSenderId: '887752712451',
    projectId: 'exospark',
    authDomain: 'exospark.firebaseapp.com',
    storageBucket: 'exospark.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkYfscyRZ8YFlCjou_c716dJGr9UIfpiA',
    appId: '1:887752712451:android:9f722893af4dbefdff8936',
    messagingSenderId: '887752712451',
    projectId: 'exospark',
    storageBucket: 'exospark.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1tTb0QtB8JQaw87vUKzl1HJ0Kd1FFd1A',
    appId: '1:887752712451:ios:921646a9794208a4ff8936',
    messagingSenderId: '887752712451',
    projectId: 'exospark',
    storageBucket: 'exospark.firebasestorage.app',
    iosBundleId: 'com.example.exoSpark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1tTb0QtB8JQaw87vUKzl1HJ0Kd1FFd1A',
    appId: '1:887752712451:ios:921646a9794208a4ff8936',
    messagingSenderId: '887752712451',
    projectId: 'exospark',
    storageBucket: 'exospark.firebasestorage.app',
    iosBundleId: 'com.example.exoSpark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZs_IgnqW9ReEYprmZLYHH5MLRVJdXMFA',
    appId: '1:887752712451:web:0889f60108657201ff8936',
    messagingSenderId: '887752712451',
    projectId: 'exospark',
    authDomain: 'exospark.firebaseapp.com',
    storageBucket: 'exospark.firebasestorage.app',
  );
}
